//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WebDuLich.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangDetail
    {
        public int MaDH { get; set; }
        public string Ten { get; set; }
        public Nullable<decimal> TongGia { get; set; }
        public int MaTour { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
