//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WebDuLich.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TenTour { get; set; }
        public string SoNgayDi { get; set; }
        public string NgayKhoiHanh { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual DonHangDetail DonHangDetail { get; set; }
    }
}
