//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WebDuLich.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.DonHangDetails = new HashSet<DonHangDetail>();
        }
    
        public int MaTour { get; set; }
        public string TenTour { get; set; }
        public string Hinh { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string NgayKhoiHanh { get; set; }
        public string PhuongTien { get; set; }
        public string SoNgayDi { get; set; }
        public Nullable<int> Hotel_TieuChuan { get; set; }
        public Nullable<decimal> GiaNguoiLon { get; set; }
        public Nullable<decimal> GiaTreEm { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangDetail> DonHangDetails { get; set; }
    }
}
